### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by rdshft** [redshifttt/pyfeed#1]
Lots.... - jokes aside:

- [ ] Un-hardcode a bunch of variables such as ANSI escape codes and date formatting
- [ ] Modularize the methods
- [ ] Asynchronous parsing of feeds
- [ ] Docs
- [ ] Article content parser

For now this is all I can think of but the list will grow.
